<?php 
	$helper = Mage::helper('blog');
	$tagCloudList = $this->getTagCloud();
	$numberShowTag = Mage::getStoreConfig('blog/menu/tag_display');
?>
<div class="block em_block-tag-cloud">
<?php if($numberShowTag>0):?>
    <?php if( count($tagCloudList) > 0 ): ?>    
    	<div class="block-title">
    		<strong><span><?php echo $this->__('Tag Cloud'); ?></span></strong>
    	</div>
    	<?php ?>
    	<div class="block-content">
    		<ul>
    			<?php for ($i = 0;$i < min(count($tagCloudList),$numberShowTag);$i++): ?>
    			<li class="item"><a href="<?php echo $helper->getBlogUrl('tag/'.$tagCloudList[$i]['url'].'.html'); ?>" style="font-size:<?php echo $tagCloudList[$i]['size'].'px'; ?>;"><?php echo $this->escapeHtml($tagCloudList[$i]['name']); ?></a></li>
    			<?php endfor; ?>
    		</ul>
    		<div class="actions">
    			<a href="<?php echo $helper->getBlogUrl('tag/taglist');?>"><?php echo $this->__('View All Tags')?></a>
    		</div>
    	</div>    
    <?php endif;?>
<?php endif;?>
</div>