<!--<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <ul>  
        <li>
        &nbsp
    </li>    
    <li>     
        <input type="radio" style="margin-left: 20px;" id="paysix" name="payment[pay_installment]" value="6" checked>
        <label for="paysix" style="float:left">6 Months</label>    

        <input type="radio" style="margin-left: 10px;" id="paytwelve" name="payment[pay_installment]" value="12">
        <label for="paytwelve">12 Months</label>    
    </li>
    </ul>
</div>-->