<div class="visible-sm visible-md visible-lg">
	<?php
		/* get config from themesetting */
		$setting = Mage::helper('em0121settings');
		$fonts = Mage::getModel('em0121settings/config_font')->toOptionArray();
		$bg_url="skin/frontend/default/em0121/images/stripes/";
		$boxwide = Mage::getModel('em0121settings/config_boxwide')->toOptionArray();
        $ischecked = $setting->getGeneral_WideslideFull();
	?>
	<a href="javascript:void(0)" class="btn-toggle">+ open/close</a>
	<div id="demotool_variation">
		<div class="variation-cp" style="display:none">
			<div class="demotool-title">Magento Theme Variations</div>
			<form method="get" id="emvariationform" action="<?php echo $this->getSkinUrl('css/variation.php') ?>">
				<div class="demotool-content">
					<!-- Google Fonts -->
					<div class="demo demo-google-fonts">
						<div class="content-title"><span>Google Fonts</span></div>
						<div class="wrapper-content google-fonts-setting">
							<div class="box last">
								<div class="content">
									<div class="col">
										<div class="row">
											<div class="label">Import these google fonts</div>
											<div class="input">
												<select id="em_variation_google_font" multiple="multiple" rows='10' size='10' >
													<?php $selectedFonts = explode(',', $setting->getTypography_GoogleFonts()) ?>
													<?php foreach ($fonts as $_font): ?>
													<option value="<?php echo htmlspecialchars($_font['value']) ?>" <?php echo @in_array($_font['value'], $selectedFonts) ? 'selected="selected"' : '' ?>><?php echo $_font['label'] ?></option>
													<?php endforeach ?>
												</select>
											</div>
											<div class="desc">Select which google fonts should be imported to your site</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Element Fonts -->
					<div class="demo demo-fonts">
						<div class="content-title"><span>Element Fonts</span></div>
						<div class="wrapper-content fonts-setting">
							<div class="box last">
								<div class="content">
									<div class="col">
										<div class="row">
											<div class="label">General Font</div>
											<div class="input"><input type="text" name="general_font" value="<?php echo htmlspecialchars($setting->getTypography_GeneralFont()) ?>" class="input-text"/></div>
											<div class="desc">Font for body, content, text...<br/>E.g. <em>normal 13px/1.35 Arial,Helvetica,sans-serif</em></div>
										</div>
										<div class="row">
											<div class="label">Title Font</div>
											<div class="input"><input type="text" name="title_font" value="<?php echo htmlspecialchars($setting->getTypography_TitleFont()) ?>" class="input-text"/></div>
											<div class="desc">Font for body, content, text...<br/>E.g. <em>500 15px/1.35 Raleway,Arial,Helvetica,sans-serif</em></div>
										</div>
										<div class="row">
											<div class="label">H1</div>
											<div class="input"><input type="text" name="h1_font" value="<?php echo htmlspecialchars($setting->getTypography_H1Font()) ?>" class="input-text" /></div>
											<div class="desc">Font of H1 element and other similar h1 heading.<br/>E.g. <em>normal 20px/1.35 Archivo Narrow, Helvetica, Arial</em></div>
										</div>
										<div class="row">
											<div class="label">H2</div>
											<div class="input"><input type="text" name="h2_font" value="<?php echo htmlspecialchars($setting->getTypography_H2Font()) ?>" class="input-text" /></div>
											<div class="desc">Font of H2 element and other similar h2 heading.<br/>E.g. <em>normal 18px/1.35 Archivo Narrow, Helvetica, Arial</em></div>
										</div>
										<div class="row">
											<div class="label">H3</div>
											<div class="input"><input type="text" name="h3_font" value="<?php echo htmlspecialchars($setting->getTypography_H3Font()) ?>" class="input-text" /></div>
											<div class="desc">Font of H3 element and other similar h3 heading.<br/>E.g. <em>normal 16px/1.35 Archivo Narrow, Helvetica, Arial</em></div>
										</div>
										<div class="row">
											<div class="label">H4</div>
											<div class="input"><input type="text" name="h4_font" value="<?php echo htmlspecialchars($setting->getTypography_H4Font()) ?>" class="input-text" /></div>
											<div class="desc">Font of H4 element and other similar h4 heading.<br/>E.g. <em>normal 14px/1.35 Archivo Narrow, Helvetica, Arial</em></div>
										</div>
										<div class="row">
											<div class="label">H5</div>
											<div class="input"><input type="text" name="h5_font" value="<?php echo htmlspecialchars($setting->getTypography_H5Font()) ?>" class="input-text" /></div>
											<div class="desc">Font of H5 element and other similar h5 heading.<br/>E.g. <em>normal 12px/1.35 Archivo Narrow, Helvetica, Arial</em></div>
										</div>
										<div class="row">
											<div class="label">H6</div>
											<div class="input"><input type="text" name="h6_font" value="<?php echo htmlspecialchars($setting->getTypography_H6Font()) ?>" class="input-text" /></div>
											<div class="desc">Font of H5 element and other similar h5 heading.<br/>E.g. <em>normal 12px/1.35 Archivo Narrow, Helvetica, Arial</em></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- General -->
					<div class="demo demo-general">
						<div class="content-title"><span>General Config</span></div>
						<div class="wrapper-content general-setting">
							<div class="box last">
								<div class="content">
									<div class="col">
										<div class="row">
											<div class="label">Box/Wide Mode</div>
											<div class="input">
												<select id="em_box_wide" name="em_box_wide" class="em_box_wide select">
													<?php $selectedBoxWide = explode(',', $setting->getGeneral_BoxWide()) ?>
													<?php foreach ($boxwide as $boxwide_item): ?>
													<option value="<?php echo htmlspecialchars($boxwide_item['value']) ?>" <?php echo @in_array($boxwide_item['value'], $selectedBoxWide) ? 'selected="selected"' : '' ?>><?php echo $boxwide_item['label'] ?></option>
													<?php endforeach ?>
												</select>
											</div>
											<div class="desc">Default: Wide</div>
										</div>
										<div class="row" id="emoption_wideslideshow">
											<div class="input">
												<input  id="wide_full" class="full_slideshow" type="checkbox" name="wide_full" value="wide_full" <?php if($ischecked!=0):?>checked<?php endif;?> /><span>Full Slideshow</span>
											</div>
										</div>
										<div id="page_boxconfig">
											<div class="row">
												<div class="label">Page Background Color</div>
												<div class="input"><input type="text" name="page_bg_color" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgColor()) ?>" class="color-picker" /></div>
												<div class="desc">Default #ffffff</div>
											</div>
											<div class="row">
												<div class="label">Page Background Pattern</div>
												<div class="input">
													<input type="hidden" name="page_bg_image" value="<?php echo htmlspecialchars($setting->getTypography_PageBgImage()) ?>"  />
													<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0121/images/stripes/'; ?>                                 
													<?php foreach (Mage::getModel('em0121settings/config_stripes')->toOptionArray() as $row):?>
													<?php $img_url = $imgDir . $row['value']; ?>
													<?php $imgBgUrl = $bg_url . $row['value']; ?>
													<a href="#" class="page_bg_image" data-input-value="<?php echo $imgBgUrl; ?>" <?php echo $setting->getTypography_PageBgImage() == $row['value'] ? 'style="selected=\'selected\'"' : '' ?>>
													<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $img_url ?>)" alt="" />
													</a>
													<?php endforeach ?>
												</div>
												<div class="desc">Specify background pattern image.</div>
											</div>
											<div class="row">
												<div class="label">Page Background Position</div>
												<div class="input"><input type="text" name="page_bg_position" value="<?php echo htmlspecialchars($setting->getTypography_PageBgPosition()) ?>" class="input-text"/></div>
												<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
											</div>
											<div class="row">
												<div class="label">Page Background Repeat</div>
												<div class="input"><input type="text" name="page_bg_repeat" value="<?php echo htmlspecialchars($setting->getTypography_PageBgRepeat()) ?>" class="input-text"/></div>
												<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
											</div>											
										</div>
                                        <div class="row">
											<div class="label">Box Shadow</div>
											<div class="input"><input type="text" name="box_shadow" value="<?php echo htmlspecialchars($setting->getTypography_BoxShadow()) ?>" class="input-text"/></div>
											<div class="desc">Configure box shadow for hover product<br/>Default: 0 0 5px #c4c4c3</div>
										</div>
										<div class="row">
											<div class="label">Rounded Corner</div>
											<div class="input"><input type="text" name="rounded_corner" value="<?php echo htmlspecialchars($setting->getTypography_RoundedCorner()) ?>" class="input-text"/></div>
											<div class="desc">Default: 0</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Header -->
					<div class="demo demo-header">
						<div class="content-title"><span>Header</span></div>
						<div class="wrapper-content header-setting">
							<div class="box last">
								<div class="content">
									<div class="col col-1">
										<div class="row">
											<div class="label">Header Background Color</div>
											<div class="input"><input type="text" name="header_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgColor()) ?>" class="color-picker" /></div>
											<div class="desc">Color of 45 degrees strip.<br/>Syntax: #number or rgba(...)<br/> Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Header Background Title Dropdown Cart Color</div>
											<div class="input"><input type="text" name="header_bg4_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBg4Color()) ?>" class="color-picker" /></div>
											<div class="desc">Color of 45 degrees strip.<br/>Syntax: #number or rgba(...)<br/> Default: #1a80ff</div>
										</div>
										<div class="row">
											<div class="label">Header Text Hover/Active Color</div>
											<div class="input"><input type="text" name="header_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText2Color()) ?>" class="color-picker" /></div>
											<div class="desc">Line-color of search textbox and search button.<br/> Default: #0072ff</div>
										</div>
										<div class="row">
											<div class="label">Header Text DropDown Cart Color</div>
											<div class="input"><input type="text" name="header_text5_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText5Color()) ?>" class="color-picker" /></div>
											<div class="desc">Text-color of messages, sign in, sign up, .... links.<br/> Default: #000000</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Header Background Bottom Color</div>
											<div class="input"><input type="text" name="header_bg2_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBg2Color()) ?>" class="color-picker" /></div>
											<div class="desc">Main background color of header.<br/> Default: #0072ff</div>
										</div>
										<div class="row">
											<div class="label">Header Background Title Menu Color</div>
											<div class="input"><input type="text" name="header_bg5_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBg5Color()) ?>" class="color-picker" /></div>
											<div class="desc">Color of 45 degrees strip.<br/>Syntax: #number or rgba(...)<br/> Default: #005bcc</div>
										</div>
										<div class="row">
											<div class="label">Header Text Phone Number Color</div>
											<div class="input"><input type="text" name="header_text3_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText3Color()) ?>" class="color-picker" /></div>
											<div class="desc">Text-color of messages, sign in, sign up, .... links.<br/> Default: #ff8401</div>
										</div>
										<div class="row">
											<div class="label">Header Line Color</div>
											<div class="input"><input type="text" name="header_line_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderLineColor()) ?>" class="color-picker" /></div>
											<div class="desc">Line-color of dropdown shopping cart.<br/> Default: #d3d3d3</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Header Background Dropdowns Color</div>
											<div class="input"><input type="text" name="header_bg3_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBg3Color()) ?>" class="color-picker" /></div>
											<div class="desc">Background color of dropdowns.<br/> Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Header Text Color</div>
											<div class="input"><input type="text" name="header_text_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderTextColor()) ?>" class="color-picker" /></div>
											<div class="desc">Background color of dropdowns cart button.<br/> Default: #666666</div>
										</div>
										<div class="row">
											<div class="label">Header Text Title Menu, Title Dropdown Cart Color</div>
											<div class="input"><input type="text" name="header_text4_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText4Color()) ?>" class="color-picker" /></div>
											<div class="desc">Text-color of messages, sign in, sign up, .... links.<br/> Default: #ffffff</div>
										</div>
									</div>
									<div class="col">
										<div class="row">
											<div class="label">Header Background Pattern</div>
											<div class="input">
												<input type="hidden" name="header_bg_image" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgImage()) ?>"  />
												<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0121/images/stripes/'; ?>                                 
												<?php foreach (Mage::getModel('em0121settings/config_stripes')->toOptionArray() as $row):?>
												<?php $img_url = $imgDir . $row['value']; ?>
												<?php $imgBgUrl = $bg_url . $row['value']; ?>
												<a href="#" class="header_bg_image" data-input-value="<?php echo $imgBgUrl; ?>" <?php echo $setting->getTypography_HeaderBgImage() == $row['value'] ? 'style="selected=\'selected\'"' : '' ?>>
												<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $img_url ?>)" alt="" />
												</a>
												<?php endforeach ?>
											</div>
											<div class="desc">Specify background pattern image.</div>
										</div>
										<div class="row">
											<div class="label">Header Background Position</div>
											<div class="input"><input type="text" name="header_bg_position" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgPosition()) ?>" class="input-text"/></div>
											<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
										</div>
										<div class="row">
											<div class="label">Header Background Repeat</div>
											<div class="input"><input type="text" name="header_bg_repeat" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgRepeat()) ?>" class="input-text"/></div>
											<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Top Menu -->
					<div class="demo demo-topmenu">
						<div class="content-title"><span>Top Menu</span></div>
						<div class="wrapper-content topmenu-setting">
							<div class="box last">
								<div class="content">
									<div class="col col-1">
										<div class="row">
											<div class="label">Top Menu Hover Background Color</div>
											<div class="input"><input type="text" name="topmenu_hover_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuHoverBgColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Top Menu Line Color</div>
											<div class="input"><input type="text" name="topmenu_line_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuLineColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #ff8401</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Top Menu Text Color</div>
											<div class="input"><input type="text" name="topmenu_text_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuTextColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #3b3b3b</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Top Menu Hover Text Color</div>
											<div class="input"><input type="text" name="topmenu_hover_text_color" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuHoverTextColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #ff8401</div>
										</div>
									</div>
									<div class="col">
										<div class="row">
											<div class="label">Top Menu Font</div>
											<div class="input"><input type="text" name="topmenu_font" value="<?php echo htmlspecialchars($setting->getTypography_TopmenuFont()) ?>" class="input-text"/></div>
											<div class="desc">Default: normal 18px/1.35 Arial,Helvetica,sans-serif</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Dropdown Menu -->
					<div class="demo demo-dropmenu">
						<div class="content-title"><span>Dropdown Menu</span></div>
						<div class="wrapper-content dropmenu-setting">
							<div class="box last">
								<div class="content">
									<div class="col col-1">
										<div class="row">
											<div class="label">Dropdown Menu Background Color</div>
											<div class="input"><input type="text" name="dropmenu_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuBgColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #ffffff<br/><br/><br/></div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Dropdown Menu Text Color</div>
											<div class="input"><input type="text" name="dropmenu_text_color" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuTextColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default text color used normal text.<br/>Default: #666666</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Dropdown Menu Title, Hover/Active Color</div>
											<div class="input"><input type="text" name="dropmenu_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuText2Color()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #0072ff</div>
										</div>
									</div>
									<div class="col">
										<div class="row">
											<div class="label">Dropdown Menu Font</div>
											<div class="input"><input type="text" name="dropmenu_font" value="<?php echo htmlspecialchars($setting->getTypography_DropmenuFont()) ?>" class="input-text"/></div>
											<div class="desc">Default font used normal text.<br/>Default: normal 13px/1.35 Arial,Helvetica,sans-serif</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Body -->
					<div class="demo demo-body">
						<div class="content-title"><span>Body</span></div>
						<div class="wrapper-content body-setting">
							<div class="box last">
								<div class="content">
									<div class="col col-1">
										<div class="row">
											<div class="label">Body Background Color</div>
											<div class="input"><input type="text" name="body_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgColor()) ?>" class="color-picker" /></div>
											<div class="desc">Color of 45 degrees strip.<br/>Syntax: #number or rgba(...)<br/> Default: #f6f6f6</div>
										</div>
										<div class="row">
											<div class="label">Body Background Title Block Color</div>
											<div class="input"><input type="text" name="body_bg4_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBg4Color()) ?>" class="color-picker" /></div>
											<div class="desc">Background color of dropdowns.<br/> Default: #0072ff</div>
										</div>
										<div class="row">
											<div class="label">Body Text Title Block Color</div>
											<div class="input"><input type="text" name="body_text_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyTextColor()) ?>" class="color-picker" /></div>
											<div class="desc">Background color of dropdowns cart button.<br/> Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Body Text Old Price, Breadcrumbs Color</div>
											<div class="input"><input type="text" name="body_text4_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyText4Color()) ?>" class="color-picker" /></div>
											<div class="desc"> Default: #999999</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Body Background Slideshow, Breadcrumbs Color</div>
											<div class="input"><input type="text" name="body_bg2_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBg2Color()) ?>" class="color-picker" /></div>
											<div class="desc">Main background color of header.<br/> Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Body Background Title Tab Color</div>
											<div class="input"><input type="text" name="body_bg5_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBg5Color()) ?>" class="color-picker" /></div>
											<div class="desc">Background color of dropdowns.<br/> Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Body Text Color</div>
											<div class="input"><input type="text" name="body_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyText2Color()) ?>" class="color-picker" /></div>
											<div class="desc">Line-color of search textbox and search button.<br/> Default: #666666</div>
										</div>
										<div class="row">
											<div class="label">Body Text Hover/Active Color</div>
											<div class="input"><input type="text" name="body_text5_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyText5Color()) ?>" class="color-picker" /></div>
											<div class="desc">Text-color of messages, sign in, sign up, .... links.<br/> Default: #0072ff</div>
										</div>
										<div class="row">
											<div class="label">Body Line Color</div>
											<div class="input"><input type="text" name="body_line_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyLineColor()) ?>" class="color-picker" /></div>
											<div class="desc">Line-color of dropdown shopping cart.<br/> Default: #d1d1d1</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Body Background Box, Slider, Block Color</div>
											<div class="input"><input type="text" name="body_bg3_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBg3Color()) ?>" class="color-picker" /></div>
											<div class="desc">Background color of dropdowns.<br/> Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Body Background Title Table Color</div>
											<div class="input"><input type="text" name="body_bg6_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyBg6Color()) ?>" class="color-picker" /></div>
											<div class="desc">Background color of dropdowns.<br/> Default: #f6f6f6</div>
										</div>
										<div class="row">
											<div class="label">Body Text Product Name, Price, Title Slider, Title Page Color</div>
											<div class="input"><input type="text" name="body_text3_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyText3Color()) ?>" class="color-picker" /></div>
											<div class="desc">Text-color of messages, sign in, sign up, .... links.<br/> Default: #000000</div>
										</div>
										<div class="row">
											<div class="label">Body Text Hover/Active Title Tab Color</div>
											<div class="input"><input type="text" name="body_text6_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyText6Color()) ?>" class="color-picker" /></div>
											<div class="desc">Text-color of messages, sign in, sign up, .... links.<br/> Default: #ff8401</div>
										</div>
										<div class="row">
											<div class="label">Body Line Title Color</div>
											<div class="input"><input type="text" name="body_line2_color" value="<?php echo htmlspecialchars($setting->getTypography_BodyLine2Color()) ?>" class="color-picker" /></div>
											<div class="desc"><br/> Default: #eaeaea</div>
										</div>
									</div>
									<div class="col">
										<div class="row">
											<div class="label">Body Background Pattern</div>
											<div class="input">
												<input type="hidden" name="body_bg_image" value="<?php echo htmlspecialchars($setting->getTypography_BodyBgImage()) ?>"  />
												<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0121/images/stripes/'; ?>                                 
												<?php foreach (Mage::getModel('em0121settings/config_stripes')->toOptionArray() as $row):?>
												<?php $img_url = $imgDir . $row['value']; ?>
												<?php $imgBgUrl = $bg_url . $row['value']; ?>
												<a href="#" class="body_bg_image" data-input-value="<?php echo $imgBgUrl; ?>" <?php echo $setting->getTypography_BodyBgImage() == $row['value'] ? 'style="selected=\'selected\'"' : '' ?>>
												<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $img_url ?>)" alt="" />
												</a>
												<?php endforeach ?>
											</div>
											<div class="desc">Specify background pattern image.</div>
										</div>
										<div class="row">
											<div class="label">Body Background Position</div>
											<div class="input"><input type="text" name="header_bg_position" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgPosition()) ?>" class="input-text"/></div>
											<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
										</div>
										<div class="row">
											<div class="label">Body Background Repeat</div>
											<div class="input"><input type="text" name="header_bg_repeat" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgRepeat()) ?>" class="input-text"/></div>
											<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Footer -->
					<div class="demo demo-footer">
						<div class="content-title"><span>Footer</span></div>
						<div class="wrapper-content footer-setting">
							<div class="box last">
								<div class="content">
									<div class="col col-1">
										<div class="row">
											<div class="label">Footer Background Color</div>
											<div class="input"><input type="text" name="footer_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBgColor()) ?>" class="color-picker" /></div>
											<div class="desc">Color of 45 degrees strip.<br/>Syntax: #number or rgba(...)<br/> Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Footer Background Color 4</div>
											<div class="input"><input type="text" name="footer_bg4_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderBg4Color()) ?>" class="color-picker" /></div>
											<div class="desc">Color of 45 degrees strip.<br/>Syntax: #number or rgba(...)<br/> Default: #f2f2f2</div>
										</div>
										<div class="row">
											<div class="label">Footer Text Color</div>
											<div class="input"><input type="text" name="footer_text_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderTextColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #666666</div>
										</div>
										<div class="row">
											<div class="label">Footer Text 4 Color</div>
											<div class="input"><input type="text" name="footer_text4_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderText4Color()) ?>" class="color-picker" /></div>
											<div class="desc"> Default: #999999</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Footer Background Bottom Color</div>
											<div class="input"><input type="text" name="footer_bg2_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterBg2Color()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Footer Text Title Color</div>
											<div class="input"><input type="text" name="footer_text2_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterText2Color()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #000000</div>
										</div>
										<div class="row">
											<div class="label">Footer Line Color</div>
											<div class="input"><input type="text" name="footer_line_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterLineColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #d9d9d9</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Footer Background Newsletter Color</div>
											<div class="input"><input type="text" name="footer_bg3_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterBg3Color()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #ffffff</div>
										</div>
										<div class="row">
											<div class="label">Footer Text Color Of Blog Name, Hover Link</div>
											<div class="input"><input type="text" name="footer_text3_color" value="<?php echo htmlspecialchars($setting->getTypography_FooterText3Color()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #0072ff</div>
										</div>
										<div class="row">
											<div class="label">Footer Line Bottom Color</div>
											<div class="input"><input type="text" name="footer_line2_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderLine2Color()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #d9d9d9</div>
										</div>
										<div class="row">
											<div class="label">Footer Input Newsletter Line Color</div>
											<div class="input"><input type="text" name="footer_line3_color" value="<?php echo htmlspecialchars($setting->getTypography_HeaderLine2Color()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #d9d9d9</div>
										</div>
									</div>
									<div class="col">
										<div class="row">
											<div class="label">Footer Background Pattern</div>
											<div class="input">
												<input type="hidden" name="footer_bg_image" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgImage()) ?>"  />
												<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/em0121/images/stripes/'; ?>                                 
												<?php foreach (Mage::getModel('em0121settings/config_stripes')->toOptionArray() as $row):?>
												<?php $img_url = $imgDir . $row['value']; ?>
												<?php $imgBgUrl = $bg_url . $row['value']; ?>
												<a href="#" class="footer_bg_image" data-input-value="<?php echo $imgBgUrl; ?>" <?php echo $setting->getTypography_FooterBgImage() == $row['value'] ? 'style="selected=\'selected\'"' : '' ?>>
												<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $img_url ?>)" alt="" />
												</a>
												<?php endforeach ?>
											</div>
											<div class="desc">Specify background pattern image.</div>
										</div>
										<div class="row">
											<div class="label">Footer Background Position</div>
											<div class="input"><input type="text" name="footer_bg_position" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgPosition()) ?>" class="input-text"/></div>
											<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
										</div>
										<div class="row">
											<div class="label">Footer Background Repeat</div>
											<div class="input"><input type="text" name="footer_bg_repeat" value="<?php echo htmlspecialchars($setting->getTypography_FooterBgRepeat()) ?>" class="input-text"/></div>
											<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Button 1 -->
					<div class="demo demo-button1">
						<div class="content-title"><span>Button 1 (Button defaut, add to cart)</span></div>
						<div class="wrapper-content button1-setting">
							<div class="box last">
								<div class="content">
									<div class="col col-1">
										<div class="row">
											<div class="label">Button 1 Background Color</div>
											<div class="input"><input type="text" name="btn1_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn1BgColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #ffffff<br/><br/><br/></div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Button 1 Text Color</div>
											<div class="input"><input type="text" name="btn1_text_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn1TextColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default text color used normal text.<br/>Default: #8c8c8c</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Button 1 Line Color</div>
											<div class="input"><input type="text" name="btn1_line_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn1LineColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #fc4c4e</div>
										</div>
									</div>
									<div class="col">
										<div class="row">
											<div class="label">Button 1 Font</div>
											<div class="input"><input type="text" name="btn1_font" value="<?php echo htmlspecialchars($setting->getTypography_Btn1Font()) ?>" class="input-text"/></div>
											<div class="desc">Default font used normal text.<br/>Default: normal 13px/1.35 Arial,Helvetica,sans-serif</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Button 2 -->
					<div class="demo demo-button2">
						<div class="content-title"><span>Button 2 (Button sidebar)</span></div>
						<div class="wrapper-content button2-setting">
							<div class="box last">
								<div class="content">
									<div class="col col-1">
										<div class="row">
											<div class="label">Button 2 Background Color</div>
											<div class="input"><input type="text" name="btn2_bg_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn2BgColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #ffffff<br/><br/><br/></div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Button 2 Text Color</div>
											<div class="input"><input type="text" name="btn2_text_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn2TextColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default text color used normal text.<br/>Default: #8c8c8c</div>
										</div>
									</div>
									<div class="col col-1">
										<div class="row">
											<div class="label">Button 2 Line Color</div>
											<div class="input"><input type="text" name="btn2_line_color" value="<?php echo htmlspecialchars($setting->getTypography_Btn2LineColor()) ?>" class="color-picker" /></div>
											<div class="desc">Default: #fc4c4e</div>
										</div>
									</div>
									<div class="col">
										<div class="row">
											<div class="label">Button 2 Font</div>
											<div class="input"><input type="text" name="btn2_font" value="<?php echo htmlspecialchars($setting->getTypography_Btn2Font()) ?>" class="input-text"/></div>
											<div class="desc">Default font used normal text.<br/>Default: normal 13px/1.35 Arial,Helvetica,sans-serif</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					<a href="#" class="btn btn-primary btn-default reset-button" data-loading-text="Resetting..." >Reset</a>                    
				</div>
				<div class="copyright">Theme designed by <a href="http://galathemes.com/" title="Premium Magento Themes &amp; Premium Magento Templates" target="_blank">Galathemes.com</a></div>
			</form>
		</div>
	</div>
</div>