<?php if(Mage::getStoreConfig('blog/menu/show_recent_post')):?>
<?php 
	$helperBlog = Mage::helper('blog');
	$thumnailWidth = 135;
	$thumnailHeight = 68;
?>
<div class="em_block-recent-post-footer">
    <div class="recent-content">
        <?php if (count($this->getRecentPost())>0):?>
        <ol>
            <?php $i =0; foreach ($this->getRecentPost() as $p): ?>
                <li class="item">
					<div class="left-area">
						<a href="<?php echo $p->getPostUrl();?>">
							<img src="<?php echo $helperBlog->resizeImage($p->getImage(),$thumnailWidth,$thumnailHeight,"emblog/post",'thumbnail');?>" alt="" />
						</a>
					</div>
					<div class="right-area">
						<p class="title"><a class="post-title" href="<?php echo $p->getPostUrl(false);?>" ><?php echo $p->getTitle();?></a></p>
						<?php $date = new DateTime($p->getCreatedAt());?>
						<small class="time-stamp"><?php echo $date->format('M j Y'); ?></small> 
						<span class="comment-count">
							<?php echo count($this->getCommentByPostinRecent($p->getId()))." Comments"; ?>
						</span>
						<?php 
							$shortdes =  $p->getPostIntro();
							if(strlen($shortdes)>150) { //dem ki tu chuoi $str, 70 la chieu dai muon quy dinh
								$strCutTitle = substr($shortdes, 0, 150); //cat 70 ki tu dau
								$shortdes = substr($strCutTitle, 0, strrpos($strCutTitle, ' '));
							}
						?>
						<div class="desc"><?php echo $this->stripTags($shortdes).'...';?></div>
					</div>
                </li>
            <?php $i++; if ($i ==1) break;?>
            <?php endforeach; ?>
        </ol>
        <?php else:?>
        	<p class="empty"><?php echo $this->__('No recent post') ?></p>
        <?php endif;?>
    </div>
</div>
<?php endif;?>